comment on table eba_cust_administrators is
    'Stores the login name who have administration rights.';

comment on column eba_cust_administrators.app_user is
    'The login name of user who have administration rights.';

comment on column eba_cust_administrators.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_administrators.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_administrators.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_administrators.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_administrators.updated_by is
    'The user who last updated the record, automatically updated.';


-- sqlcl_snapshot {"hash":"fe688d30c59e1f692b5d28dbca6d416357bdf5cf","type":"COMMENT","name":"eba_cust_administrators","schemaName":"prlnu","sxml":""}