comment on table eba_cust_links is
    'Stores various Links pointing to the Contacts.';

comment on column eba_cust_links.contact_id is
    'The ID of the Contact, the value is referred from ID field in eba_cust_contacts.';

comment on column eba_cust_links.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_links.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_links.customer_id is
    'The ID of the Customer, the value is referred from ID field in eba_cust_customers.';

comment on column eba_cust_links.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_links.link is
    'The link which points to the additional data.';

comment on column eba_cust_links.link_type is
    'The type of link.';

comment on column eba_cust_links.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_links.updated_by is
    'The user who last updated the record, automatically updated.';


-- sqlcl_snapshot {"hash":"c6fd5f0b2eed0c430f02b9d87c63593b6334ed15","type":"COMMENT","name":"eba_cust_links","schemaName":"prlnu","sxml":""}