comment on table eba_cust_customers is
    'Stores Customer information.';

comment on column eba_cust_customers.category_id is
    'The Category in which the customer belongs.';

comment on column eba_cust_customers.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_customers.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_customers.customer_name is
    'The name for the Customer.';

comment on column eba_cust_customers.duns is
    'Unique nine-digit identification sequence of Customer''s Business..';

comment on column eba_cust_customers.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_customers.number_of_users is
    'The number of users for your Customer.';

comment on column eba_cust_customers.referencable is
    'Is the Customer referencable.';

comment on column eba_cust_customers.sic is
    'The Standard Industry Code of the Customer.';

comment on column eba_cust_customers.status_id is
    'The Status of the Customer.';

comment on column eba_cust_customers.stock_symbol is
    'The Stock symbol of the Customer.';

comment on column eba_cust_customers.summary is
    'Short summary about the Customer.';

comment on column eba_cust_customers.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_customers.updated_by is
    'The user who last updated the record, automatically updated.';

comment on column eba_cust_customers.web_site is
    'The URL of the Customer''s Web site.';


-- sqlcl_snapshot {"hash":"4541bbe330d244db9b3e91627dcd38263c162b79","type":"COMMENT","name":"eba_cust_customers","schemaName":"prlnu","sxml":""}