comment on table eba_cust_views_log is
    'Stores the count of Customer & Contacts being viewed.';

comment on column eba_cust_views_log.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_views_log.table_primary_id is
    'The primary key value of Customer or Contact table.';

comment on column eba_cust_views_log.view_count is
    'Total number of times the Customer details or Contact details been viewed.';

comment on column eba_cust_views_log.view_type is
    'The type of view, either "CUS" - Customer or "CON" - Contact.';


-- sqlcl_snapshot {"hash":"0021aa09b4e9a8de51333a637d83eb414d4dbf11","type":"COMMENT","name":"eba_cust_views_log","schemaName":"prlnu","sxml":""}