comment on table eba_cust_categories is
    'Stores Category information.';

comment on column eba_cust_categories.category is
    'The unique name for the Category.';

comment on column eba_cust_categories.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_categories.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_categories.description is
    'A brief description about the Category.';

comment on column eba_cust_categories.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_categories.is_active is
    'Used to Enable or Disable a Category from being used in the transaction.';

comment on column eba_cust_categories.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_categories.updated_by is
    'The user who last updated the record, automatically updated.';


-- sqlcl_snapshot {"hash":"c9e7153dee7cbfb1a0d2b8195eedd54f87f51f56","type":"COMMENT","name":"eba_cust_categories","schemaName":"prlnu","sxml":""}