comment on table eba_cust_contacts is
    'Stores Contact information.';

comment on column eba_cust_contacts.address_line1 is
    'Address of the Contact.';

comment on column eba_cust_contacts.address_line2 is
    'Address of the Contact.';

comment on column eba_cust_contacts.cell_phone is
    'The Mobile phone number.';

comment on column eba_cust_contacts.city is
    'The name of the City.';

comment on column eba_cust_contacts.company is
    'The Company name of the Contact.';

comment on column eba_cust_contacts.contact_type_id is
    'The type of Contact, the value is referred from ID field in eba_cust_contact_types.';

comment on column eba_cust_contacts.country is
    'The name of the Country.';

comment on column eba_cust_contacts.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_contacts.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_contacts.email is
    'The Email address.';

comment on column eba_cust_contacts.fax is
    'The Fax number.';

comment on column eba_cust_contacts.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_contacts.name is
    'The name of the Contact.';

comment on column eba_cust_contacts.notes is
    'A short Note about the Contact.';

comment on column eba_cust_contacts.phone is
    'The Phone number.';

comment on column eba_cust_contacts.state is
    'The name of the State.';

comment on column eba_cust_contacts.title is
    'The Title of the Contact.';

comment on column eba_cust_contacts.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_contacts.updated_by is
    'The user who last updated the record, automatically updated.';

comment on column eba_cust_contacts.zip is
    'The Zip code.';


-- sqlcl_snapshot {"hash":"abb8dde41b9fd07359db8e65ef7e9b3bf36dc49f","type":"COMMENT","name":"eba_cust_contacts","schemaName":"prlnu","sxml":""}