comment on table eba_cust_status is
    'Stores Status information.';

comment on column eba_cust_status.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_status.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_status.description is
    'A brief description about the Status.';

comment on column eba_cust_status.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_status.is_active is
    'Used to Enable or Disable a Customer Status from being used in the transaction.';

comment on column eba_cust_status.status is
    'The unique name for the Status.';

comment on column eba_cust_status.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_status.updated_by is
    'The user who last updated the record, automatically updated.';


-- sqlcl_snapshot {"hash":"b5ae1a7e41bf20039254b6358d8993e4c3388547","type":"COMMENT","name":"eba_cust_status","schemaName":"prlnu","sxml":""}