comment on table eba_cust_contact_types is
    'Stores information about various type of contacts.';

comment on column eba_cust_contact_types.contact_type is
    'The name for the Contact type.';

comment on column eba_cust_contact_types.created is
    'The date on which the record is created, automatically updated.';

comment on column eba_cust_contact_types.created_by is
    'The user who created the record, automatically updated.';

comment on column eba_cust_contact_types.id is
    'Primary Key, never changes.  Automatically generated by Oracle Database';

comment on column eba_cust_contact_types.is_active is
    'Used to Enable or Disable a Contact types from being used in the transaction.';

comment on column eba_cust_contact_types.updated is
    'The date on which the record is last updated, automatically updated.';

comment on column eba_cust_contact_types.updated_by is
    'The user who last updated the record, automatically updated.';


-- sqlcl_snapshot {"hash":"46fda80c03ce0240b2d52fa61751ebf1ddff6977","type":"COMMENT","name":"eba_cust_contact_types","schemaName":"prlnu","sxml":""}